name: aiSECTOR
version: 1.1
main: ai.aisector.SectorPlugin
api-version: 1.20
description: Plugin obsługujący sektory w Minecraft z wykorzystaniem Redis.
commands:
  cx:
    description: Wymień 9x64 cobble na 1–3 CobbleX
    usage: /cx
    permission: aisector.cx
  lvl:
    aliases:
      - pkt
    description: /lvl
  drop:
    description: /drop
  rang:
    permissions:
    aisector.command.rank:
      default: op
  sektor:
    description: Sprawdza, na którym sektorze jest gracz.
  send:
      description: Przenosi gracza na inny sektor.
  tpa:
    permission:
    aisector.command.tpa:
    description: Wysyła prośbę o teleportację do gracza.
  tpaccept:
    description: Akceptuje prośbę o teleportację.
  alert:
    description: Wysyła globalne ogłoszenie.
  v:
    description: Włącza/wyłącza tryb niewidzialności.
    aliases: [ vanish ]
    permissions:
    aisector.command.vanish:
      default: op
  fly:
    description: Włącza/wyłącza latanie.
    permissions:
    aisector.command.fly:
      default: op
  speed:
    description: Ustawia prędkość latania/chodzenia.
    permissions:
    aisector.command.speed:
     default: op
  heal:
    description: Leczy gracza.
    permissions:
    aisector.command.heal:
     default: op
  god:
    description: Włącza/wyłącza tryb boga.
    permissions:
    aisector.command.god:
     default: op
  wyjebane:
    description: Włącza/wyłącza prywatne wiadomości.
  s:
    description: Przywołuje gracza do siebie.
    usage: /s <gracz>
    permissions:
    aisector.command.s:
      default: op
  tp:
    description: Teleportuje do graczy w całej sieci.
    usage: /tp <gracz>
    permissions:
    aisector.command.tp:
      default: op
  setspawnsector:
    description: Ustawia globalny spawn dla serwera.
    usage: /setspawnsector
    permission: aisector.command.setspawn
  spawn: # <-- NOWA KOMENDA
    description: Teleportuje na spawn serwera.
    usage: /spawn
    permissions:
    aisector.setspawn:
      description: Pozwala na ustawienie spawnu serwera.
      default: op
  sectorinfo:
    description: Wyświetla informacje o bieżącym sektorze.
    usage: /sectorinfo
    permission: ai.sector.info
  enderchest:
    description: Otwiera Enderchest swój lub innego gracza.
    aliases: [ ec ]
  ci:
    description: Czysci caly ekwipunek gracza.
    aliases: [ clear ]
    permission: aisector.command.ci
  repair:
    description: Naprawia przedmioty.
    usage: "/<command> [all]"
    permission: aisector.command.repair.one
  naprawkilof:
    description: Naprawia kilof za diamenty.
    permission: aisector.command.naprawkilof
  gamemode:
    description: Zmienia tryb gry gracza.
    aliases: [ gm ]
    permission: aisector.command.gamemode
  weather:
    description: Zmienia pogodę na wszystkich serwerach.
    usage: "/<command> <clear|rain|thunder>"
    permission: aisector.command.weather
  time:
    description: Zmienia porę dnia na wszystkich serwerach.
    usage: "/<command> set <day|night>"
    permission: aisector.command.time
  invsee:
    description: Otwiera ekwipunek innego gracza.
    aliases: [ eq ]
    permission: aisector.command.invsee
  tppos:
    description: Teleportuje gracza na podane koordynaty, zmieniając sektor w razie potrzeby.
    usage: "/tppos <x> <y> <z>"
    permission: aisector.command.tppos
  backup:
    permission: aisector.command.backup
  sethome:
    description: Ustawia lokalizację domu.
    permission: aisector.command.sethome
  home:
    description: Teleportuje do zapisanego domu.
    permission: aisector.command.home




